name: laundry_seller
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ^3.8.1
dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.2
    flutter_riverpod: ^2.4.5
    flutter_screenutil: ^5.9.0
    flutter_svg: ^2.0.9
    hive_flutter: ^1.1.0
    dio: ^5.3.3
    pretty_dio_logger: ^1.3.1
    flutter_easyloading: ^3.0.5
    shimmer: ^3.0.0
    scrollable_positioned_list: ^0.3.8
    flutter_staggered_animations: ^1.0.0
    intl: ^0.18.1
    device_preview: ^1.1.0
    page_transition: ^2.1.0
    gap: ^3.0.1
    flutter_form_builder: ^9.1.1
    form_builder_validators: ^9.1.0
    flutter_localizations:
        sdk: flutter
    pinput: ^3.0.1
    image_picker: ^1.0.4
    cached_network_image: ^3.3.0
    flutter_switch: ^0.3.2
    table_calendar: ^3.0.9
    calendar_date_picker2: ^0.5.3
    lite_rolling_switch: ^1.0.1
    auto_size_text: ^3.0.0
    url_launcher: ^6.2.1
    flutter_html: ^3.0.0-beta.2
    path_provider: ^2.1.1
    flutter_downloader: ^1.11.5
    open_file: ^3.3.2
    flutter_spinkit: ^5.2.0
dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0
    change_app_package_name: ^1.1.0
    build_runner: null
    flutter_gen_runner: null
    intl_utils: ^2.8.5
flutter:
    uses-material-design: true
    assets:
        - assets/
        - assets/image/
        - assets/svg/
    fonts:
        -
            family: Roboto
            fonts:
                -
                    asset: assets/font/Roboto-Bold.ttf
                -
                    asset: assets/font/Roboto-Light.ttf
                -
                    asset: assets/font/Roboto-Medium.ttf
                -
                    asset: assets/font/Roboto-Regular.ttf


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
      
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
      
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
      
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
dependency_overrides:
  intl: ^0.20.2
